name: Build V8 Static Library

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      version:
        description: V8 Version
        required: false

jobs:
  build:
    name: ${{ matrix.config.name }}_${{ matrix.config.arch }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            name: linux
            arch: x64
            lib_name: libv8_monolith.a
          - os: windows-latest
            name: windows
            arch: x64
            lib_name: v8_monolith.lib
    env:
      DEPOT_TOOLS_WIN_TOOLCHAIN: 0

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.2

      - name: Install MSVC/MCBuild (Windows)
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v2

      - name: Get target V8 version
        id: version
        shell: pwsh
        run: |
          $version = Get-Content -Path V8_VERSION
          If ('${{ github.event.inputs.version }}' -ne '') { $version = "${{ github.event.inputs.version }}" }
          echo "V8_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Install depot tools
        shell: pwsh
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$pwd/depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Checkout V8 source
        run: |
          fetch v8
          cd v8
          git checkout ${{ env.V8_VERSION }}
          gclient sync

      - name: Build V8
        shell: pwsh
        run: |
          Set-Location -Path v8
          python tools/dev/v8gen.py ${{ matrix.config.arch }}.release
          Copy-Item "../platforms/${{ matrix.config.name }}_${{ matrix.config.arch }}/args.gn" -Destination "./out.gn/${{ matrix.config.arch }}.release/args.gn" -force
          gn gen out.gn/${{ matrix.config.arch }}.release
          Get-Content ./out.gn/${{ matrix.config.arch }}.release/args.gn | Write-Output
          ninja -C out.gn/${{ matrix.config.arch }}.release

      - name: Prepare out directory
        shell: pwsh
        run: |
          New-Item -ItemType directory -Path ./out/
          Copy-Item -Path ./v8/out.gn/x64.release/obj/${{ matrix.config.lib_name }} -Destination ./out/${{ matrix.config.name }}_${{ matrix.config.arch }}_${{ matrix.config.lib_name }}
          If ($IsLinux) { Copy-Item -Path ./v8/out.gn/x64.release/d8 -Destination ./out/${{ matrix.config.name }}_${{ matrix.config.arch }}_d8 }
          If ($IsWindows) { Copy-Item -Path ./v8/out.gn/x64.release/d8.exe -Destination ./out/${{ matrix.config.name }}_${{ matrix.config.arch }}_d8.exe }

      - name: Release monolithic V8 lib & d8
        uses: softprops/action-gh-release@v2
        with:
          files: ./out/*
          name: V8 Release ${{ env.V8_VERSION }}
          tag_name: v${{ env.V8_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}